// Generates controllers/consentForms.js from the patient-facing /consent/ page.
// The page is the single source of truth for the text patients read; the backend
// registry is what gets snapshotted onto every signed record.
// Usage: node scripts/genConsentForms.js [path-to-consent-index.html]
const fs = require("fs");
const path = require("path");

const SRC = process.argv[2] || "/home/aims/frontend-build/consent/index.html";
const OUT = path.join(__dirname, "..", "controllers", "consentForms.js");

const html = fs.readFileSync(SRC, "utf8");
const start = html.indexOf("const CONSENTS = {");
if (start < 0) { console.error("CONSENTS block not found in " + SRC); process.exit(1); }

// brace-walk to the matching close of the literal
let depth = 0, end = -1;
for (let i = html.indexOf("{", start); i < html.length; i++) {
  const ch = html[i];
  if (ch === "{") depth++;
  else if (ch === "}") { depth--; if (depth === 0) { end = i + 1; break; } }
}
if (end < 0) { console.error("unbalanced CONSENTS literal"); process.exit(1); }

const literal = html.slice(html.indexOf("{", start), end);
let forms;
try { forms = eval("(" + literal + ")"); } catch (e) { console.error("eval failed: " + e.message); process.exit(1); }

const byVersion = {};
for (const key of Object.keys(forms)) {
  const f = forms[key];
  if (!f.ver || !f.text) continue;
  byVersion[f.ver] = { key: key, title: f.title, proc: f.proc, screen: !!f.screen, text: f.text };
}
if (!Object.keys(byVersion).length) { console.error("no usable forms extracted"); process.exit(1); }

fs.writeFileSync(OUT,
  "// GENERATED by scripts/genConsentForms.js from " + SRC + " — do not hand-edit.\n" +
  "// Canonical consent text per version: what the patient reads is what gets stored.\n" +
  "// Re-run the generator whenever the /consent/ page text changes (bump the version too).\n" +
  "module.exports = " + JSON.stringify(byVersion, null, 2) + ";\n");
console.log("wrote " + OUT + " — versions: " + Object.keys(byVersion).join(", "));
